src/candidate/urls.py
from django.urls import path
from candidate.views import (
    CandidateLoginView,
    CandidateLogoutView,
    EditCandidateView,
    RegisterCandidateView,
    CandidateEventsView,
    CandidateDetailsView
)


urlpatterns = [
    path('register/', RegisterCandidateView.as_view(), name='register_candidate'),
    path('login/', CandidateLoginView.as_view(), name='candidate_login'),
    path('<uuid:candidate_id>/events/', CandidateEventsView.as_view(), name='candidate_events'),
    path('<uuid:candidate_id>/', CandidateDetailsView.as_view(), name='candidate_details'),
    path('<uuid:candidate_id>/edit/', EditCandidateView.as_view(), name='edit_details'),
    path('logout/', CandidateLogoutView.as_view(), name='logout_candidate')
]

src/interviewer/urls.py
from django.urls import path
from interviewer.views import (
    InterviewerLoginView,
    CandidatesListView,
    EventsListView,
    CreateInterviewerView,
    CreateEventView,
    UpdateEventView,
    DeleteEventView,
    InterviewerLogoutView
)

urlpatterns = [
    path('login/', InterviewerLoginView.as_view(), name='interviewer_login'),
    path('logout/', InterviewerLogoutView.as_view(), name='interviewer_logout'),
    path('candidate_list/', CandidatesListView.as_view(), name='candidates_list'),
    path('events/', EventsListView.as_view(), name='events'),
    path('register/', CreateInterviewerView.as_view(), name='register_interviewer'),
    path('<uuid:candidate_id>/create_event/', CreateEventView.as_view(), name='create_event'),
    path('<uuid:event_id>/update_event/', UpdateEventView.as_view(), name='update_event'),
    path('delete_event/<uuid:event_id>/', DeleteEventView.as_view(), name='delete_event'),

]

src/vgg_interview/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from interviewer.views import IndexView as HomePageView

urlpatterns = [
    re_path(r'^$', HomePageView.as_view(), name='home'),
    path('candidate/', include(('candidate.urls', 'candidate'), namespace='candidate')),
    path('interviewer/',include(('interviewer.urls', 'interviewer'), namespace='interviewer')),
]

src/interviewer/forms.py
from django import forms
from django.contrib.postgres.forms import SimpleArrayField
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import make_password
from datetime import datetime, time, timedelta
from util.checktime import is_time_between_nine_to_five
from accounts.models import Interviewer
import pytz

class InterviewerRegisterForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()
    work_start = forms.CharField()
    work_end = forms.CharField()

    def __init__(self, *args, **kwargs):
        """Set up default value for instance objects.
        """
        self.interviewer_user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        """Clean up form an run neccessary validations if any
        """

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        work_start = datetime.strptime(str(self.cleaned_data.get('work_start')), "%Y-%m-%dT%H:%M")
        work_end = datetime.strptime(str(self.cleaned_data.get('work_end')), "%Y-%m-%dT%H:%M")

        if datetime.now() >= work_end:
            raise forms.ValidationError(
                message="Work end date selected is in the past, Selct a future date", code="invalid_start_date"
            )

class UpdateInterviewerForm(forms.Form):
    work_start = forms.CharField()
    work_end = forms.CharField()

    def __init__(self, *args, **kwargs):
        """
        Set up default value for instance objects.
        """
        self.interviewer_user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        """
        Clean up form an run neccessary validations if any
        """

        work_start = self.cleaned_data.get('work_start')
        work_end = self.cleaned_data.get('work_end')

class CreateEventForm(forms.Form):
    start_date = forms.CharField()
    duration = forms.CharField()

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CreateEventForm, self).__init__(*args, **kwargs)

    def clean(self):
        """
        Clean up form an run neccessary validations if any
        """

        start_date = datetime.strptime(str(self.cleaned_data.get('start_date')), "%Y-%m-%dT%H:%M")
        duration = int(self.cleaned_data.get('duration'))

        interviewer = Interviewer.objects.get(user=self.request.user)

        utc=pytz.UTC
        if datetime.now() >= start_date:
            raise forms.ValidationError(
                message="Event start date selected is in the past, Selct a future date", code="invalid_start_date"
            )

        if utc.localize(start_date) > interviewer.work_end: # check date comes after work duration
            raise forms.ValidationError(
                message="Event start time comes after your work end date"
            )

        if not is_time_between_nine_to_five(start_date.time()): # check is between 9-5(working hours):
            raise forms.ValidationError(
                message="Event start time must be between working hours(9am-5pm)"
            )

        if duration < 1800 or duration > 3600: # check is between 9-5(working hours):
            raise forms.ValidationError(
                message="Duration must be between 1800 Seconds(30 minutes) to 3600 Seconds(1 Hour)"
            )

class InterviewerLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()

    def __init__(self, *args, **kwargs):
        """Set up default value for instance objects."""
        self.candidate_user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        """Clean up form an run neccessary validations if any
        """

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

src/interviewer/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth import login, logout
from interviewer.forms import  InterviewerLoginForm, InterviewerRegisterForm, CreateEventForm
from lib.authentication import InterviewerLoginRequiredMixin
from candidate.forms import  CandidateLoginForm, CandidateRegisterForm, UpdateCandidateForm
from accounts.models import Event, Candidate, User, Interviewer
from django.contrib import messages
from django.contrib.auth import authenticate


# Create your views here.
class IndexView(View):

    def get(self, request):
        """Render index page."""

        return render(request, 'home.html')

class CreateInterviewerView(View):
    def get(self, request):
        """Render interviewer creation page.
        """

        if request.user.is_authenticated:
            return redirect(reverse('interviewer:candidates_list'))
        form = InterviewerRegisterForm()
        return render(request, 'interviewer_register.html', {'form':form})

    def post(self, request):
        """
        Handle interviewer registration.
        """

        form = InterviewerRegisterForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.get(email=form.cleaned_data['email'])
                messages.add_message(request, messages.ERROR, 'Interviewer with same email already exists!')
                return render(request, 'interviewer_register.html', {'form': form})
            except User.DoesNotExist:
                user = User.objects.create_user(
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password']
                )
                interviewer = Interviewer.objects.create(work_start=form.cleaned_data['work_start'], user=user, work_end=form.cleaned_data['work_end'])
                return redirect(reverse('interviewer:interviewer_login'))
        return render(request, 'interviewer_register.html', {'form': form})

class InterviewerLoginView(View):
    def get(self, request):
        """Render interviewer login page.
        """

        if request.user.is_authenticated:
            return redirect(reverse('interviewer:candidates_list'))

        form = InterviewerLoginForm()
        return render(request, 'interviewer_login.html')

    def post(self, request):
        """
        Handle interviewer login.
        """

        form = InterviewerLoginForm(request.POST)
        if form.is_valid():
            interviewer_user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])

            if interviewer_user:
                login(request, interviewer_user, backend='lib.authentication.UserBackend')
                return redirect(reverse('interviewer:candidates_list'))

        messages.add_message(request, messages.ERROR, 'Invalid Login Credentials')
        return render(request, 'interviewer_login.html', {'form': form})

class CandidatesListView(InterviewerLoginRequiredMixin, View):
    def get(self, request):
        """Render candidates list page.
        """

        candidates = Candidate.objects.all()
        context = {'candidates':candidates}
        return render(request, 'candidate_list.html', context)

class EventsListView(InterviewerLoginRequiredMixin, View):
    def get(self, request):
        """Render interviewers scheduled events page.
        """
        interviewer = Interviewer.objects.get(user=request.user)
        events = interviewer.booked_events.all()
        context = {'events':events}
        return render(request, 'scheduled_events.html', context)

class CreateEventView(InterviewerLoginRequiredMixin, View):
    def get(self, request, candidate_id):
        """Render event creation page.
        """

        form = CreateEventForm()
        try:
            candidate = Candidate.objects.get(id=candidate_id)
            return render(request, 'create_event.html', {'form': form, 'candidate':candidate})
        except Candidate.DoesNotExist:
            messages.add_message(request, messages.ERROR, 'Candidate does not exist!')
            return render(request, 'create_event.html', {'form': form})

    def post(self, request, candidate_id):
        """
        Handle event creation.
        """
        candidate = Candidate.objects.get(id=candidate_id)
        form = CreateEventForm(request.POST, request=request)
        if form.is_valid():
            try:
                event = Event(
                    start=form.cleaned_data['start_date'],
                    duration=int(form.cleaned_data['duration']),
                    candidate=candidate
                    )
                interviewer = Interviewer.objects.get(user=request.user)
                book = interviewer.book(event)
                if book.get('status') == False:
                    messages.add_message(request, messages.ERROR, book.get('message'))
                    return render(request, 'create_event.html', {'form': form, 'candidate':candidate})
                messages.add_message(request, messages.SUCCESS, book.get('message'))
                return redirect(reverse('interviewer:events'))
            except Candidate.DoesNotExist:
                messages.add_message(request, messages.ERROR, 'Candidate does not exist')
                return render(request, 'create_event.html', {'form': form})
        return render(request, 'create_event.html', {'form': form, 'candidate':candidate})

class UpdateEventView(InterviewerLoginRequiredMixin, View):
    def get(self, request, event_id):
        """Render event update page.
        """

        form = CreateEventForm()
        try:
            event = Event.objects.get(id=event_id)
            candidate = event.candidate
            return render(request, 'update_event.html', {'form': form, 'candidate':candidate})
        except Candidate.DoesNotExist:
            messages.add_message(request, messages.ERROR, 'Candidate does not exist!')
            return render(request, 'update_event.html', {'form': form})

    def post(self, request, event_id):
        """
        Handle event update.
        """

        ev = Event.objects.get(id=event_id)
        candidate = ev.candidate
        form = CreateEventForm(request.POST, request=request)
        if form.is_valid():
            try:
                event = Event(
                    start=form.cleaned_data['start_date'],
                    duration=int(form.cleaned_data['duration']),
                    candidate=candidate
                    )
                interviewer = Interviewer.objects.get(user=request.user)
                book = interviewer.book(event, is_update=True)
                if book.get('status') == False:
                    messages.add_message(request, messages.ERROR, book.get('message'))
                    return render(request, 'create_event.html', {'form': form, 'candidate':candidate})
                messages.add_message(request, messages.SUCCESS, book.get('message'))
                return redirect(reverse('interviewer:events'))
            except Candidate.DoesNotExist:
                messages.add_message(request, messages.ERROR, 'Candidate does not exist')
                return render(request, 'create_event.html', {'form': form})

        return render(request, 'update_event.html', {'form': form, 'candidate':candidate})

class DeleteEventView(InterviewerLoginRequiredMixin, View):
    def get(self, request, event_id):
        """Delete Event
        """
        interviewer = Interviewer.objects.get(user=request.user)
        event = Event.objects.get(id=event_id)
        events = interviewer.booked_events.remove(event)
        event.delete()

        messages.add_message(request, messages.SUCCESS, 'Event Deleted Successfully')
        return redirect(reverse('interviewer:events'))

class InterviewerLogoutView(InterviewerLoginRequiredMixin, View):
    def get(self, request):
        """
        Logout interviewer.
        """

        request.session.flush()
        logout(request)
        return redirect(reverse('interviewer:interviewer_login'))

src/interviewer/templates/base_interview.html
<!DOCTYPE html>
<html>
<head>
  {% block title %} {% endblock title %}
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}

li {
  display: inline;
}
.content{
    display:flex;
    align-items:center;
    justify-content:center;
    height:80vh;
  }
  form {
    margin:0 auto;
    width:300px
    }
    input {
    margin-bottom:3px;
    padding:10px;
    width: 100%;
    border:1px solid #CCC
    }
    button {
    padding:10px
    }
    label {
    cursor:pointer
    }
    #form-switch {
    display:none
    }
    #register-form {
    display:none
    }
    #form-switch:checked~#register-form {
    display:block
    }
    #form-switch:checked~#login-form {
    display:none
    }
    table, th, td {
    border:1px solid black;
    }
</style>
</head>
<body>

<ul>
  <li><h3>VGG INTERVIEWER PORTAL</h3></li>
  {% block link %}{% endblock link %}
</ul>
<div style="text-align: center;">
  {% block pagetitle %} {% endblock pagetitle %}
</div>
<div class="content">
{% block content %}{% endblock content %}
</div>
</body>
</html>

src/interviewer/templates/candidate_list.html
{% extends "base_interview.html" %}
{% block title %}<title>Candidate List</title>{% endblock title %}
{% block link %}
<li><a href="{% url 'interviewer:events'%}">My Events</a></li>
<li><a href="{% url 'interviewer:interviewer_logout'%}">Logout</a></li>
{% endblock link %}
{% block pagetitle %} <h4>Candidates List</h4> {% endblock pagetitle %}
{% block content %}
        {% if candidates %}
        <table>
        <tr>
            <th>Candidate Name</th>
            <th>Stack</th>
            <th>Action</th>
        </tr>
        {% for candidate in candidates %}
        <tr>
            <td>{{candidate.name}}</td>
            <td>{{candidate.stack|join:", "}}</td>
            <td><a href="{% url 'interviewer:create_event' candidate_id=candidate.id %}">Schedule Event</a></td>
        </tr>
        {% endfor %}
        </table>
        {% else %}
            <h3>There are no candidates enrolled yet!</h3>
        {% endif %}
{% endblock content %}

src/interviewer/templates/create_event.html
{% extends "base_interview.html" %}
{% block title %}<title>Create Event</title>{% endblock title %}
{% block link %}
<li><a href="{% url 'interviewer:events'%}">My Events</a></li>
<li><a href="{% url 'interviewer:candidates_list'%}">All Candidates</a></li>
<li><a href="{% url 'interviewer:interviewer_logout'%}">Logout</a></li>
{% endblock link %}
{% block pagetitle %} <h4>Create Event</h4> {% endblock pagetitle %}
{% block content %}
    {% if form.non_field_errors %}
    <div>
        {% for err in form.non_field_errors %}
            <p>{{err}}</p>
        {% endfor %}
    </div>
    {% endif %}
    {% if messages %}
    {% for message in messages %}
      <P>{{message}}</P>
    {% endfor %}
    {% endif %}
    <form id='login-form' action="" method='POST'>
      <label for="candidate">CANDIDATE</label>
      <input id="candidate" type="text" readonly value="{{candidate.name}}" required>
      <label for="start_date">EVENT START</label>
      <input type="datetime-local" id="start_date" class="form-control" name="start_date" required placeholder="START DATE.">
      <label for="duration">DURATION(SECONDS)</label>
      <input id="duration" name="duration" type="number" placeholder="00" required>
      <button type='submit'>Create Event</button>
      {% csrf_token %}
    </form>
{% endblock content %}

src/interviewer/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Candidate Dashboard</title>
  </head>
    <style>
      body{
        display:flex;
        align-items:center;
        justify-content:center;
        height:80vh;
      }
      div.parent {
        display:inline-block;
        background-color:#eeeeee;
        width: 200px;
        height:250px;
        margin: 20px 20px;
        text-align:center;
      }
      div.parent > div {
        position:relative;
        width:150px;
        height: 150px;
        font-size:28px;
        font-weight:bold;
        margin: 25px auto;
        background-color:#ddd;
        border-radius: 50%;
        text-align:center;
        line-height: 150px;
      }
      div.parent > label {
        width: 160px;
        display:block;
        font-size: 19px;
        line-height:34px;
        color: white;
        margin:20px auto 0 auto;
        background-color:#0075ff;
        border-radius:5px;
      }
      .b::before {
        position:absolute;
        content: 'or';
        top: 25%;
        left:125%;
        font:16px bold;
        color:white;
        background-color:#0075ff;
        border-radius:50%;
        width:20px;
        height:20px;
      }
      .b::after {
        position:absolute;
        content:'';
        width:2px;
        boder-radius:100px;
        height:250px;
        left:131.5%;
        z-index:-1;
        top:-80px;
        background-color:#0075ff;
      }
    </style>
  <body>
    <div class="parent">
      <label>Interviewer</label>
    <div class="b"><a href="{% url 'interviewer:register_interviewer' %}">Register</a></div>
    </div>
    <div class="parent">
      <label>Candidate</label>
    <div><a href="{% url 'candidate:register_candidate' %}">Register</a></div>
    </div>
  </body>
</html>

src/interviewer/templates/interviewer_login.html
{% extends "base_interview.html" %}
{% block title %}<title>Interviewer Login</title>{% endblock title %}
{% block content %}
        {% if form.non_field_errors %}
        <div>
            {% for err in form.non_field_errors %}
                <p>{{err}}</p>
            {% endfor %}
        </div>
        {% endif %}
        {% if messages %}
        {% for message in messages %}
          <P>{{message}}</P>
        {% endfor %}
        {% endif %}
    <form id='login-form' action="{% url 'interviewer:interviewer_login' %}" method='POST'>
      <label for="email">EMAIL</label>
      <input id="email" name="email" type="email" placeholder="Email" required>
      <label for="password">PASSWORD</label>
      <input id="password" name="password" type="password" placeholder="Password" required>
      <button type='submit'>Login Interviewer</button>
      <p><a href="{% url 'interviewer:register_interviewer' %}">Register Instead</a></p>
      {% csrf_token %}
    </form>
  </div>
{% endblock content %}

src/interviewer/templates/interviewer_register.html
{% extends "base_interview.html" %}
{% block title %}<title>Interviewer Register</title>{% endblock title %}
{% block content %}
        {% if form.non_field_errors %}
        <div>
            {% for err in form.non_field_errors %}
                <p>{{err}}</p>
            {% endfor %}
        </div>
        {% endif %}
        {% if messages %}
        {% for message in messages %}
          <P>{{message}}</P>
        {% endfor %}
        {% endif %}
    {% if form.non_field_errors %}
    <div>
        {% for err in form.non_field_errors %}
            <p>{{err}}</p>
        {% endfor %}
    </div>
    {% endif %}
    {% if messages %}
    {% for message in messages %}
      <P>{{message}}</P>
    {% endfor %}
    {% endif %}
      <form id='login-form' action="{% url 'interviewer:register_interviewer' %}" method='POST'>
        <label for="email">EMAIL</label>
        <input name="email" type="email" id="email" placeholder="Email" required>
        <label for="password">PASSWORD</label>
        <input id="password" type="password" name="password" placeholder="Password" required>
        <label for="work_start">WORK START</label>
        <input id="work_start" type="datetime-local" id="work_start class="form-control" name="work_start" required placeholder="WORK START">
        <label for="work_end">WORK END</label>
        <input id="work_end" type="datetime-local" id="work_end" class="form-control" name="work_end" required placeholder="WORK END">
        <button type='submit'>Register Interviewer</button>
        <p><a href="{% url 'interviewer:interviewer_login' %}">Login Instead</a></p>
        {% csrf_token %}
      </form>
    </div>
{% endblock content %}

src/interviewer/templates/scheduled_events.html
{% extends "base_interview.html" %}
{% block title %}<title>Create Event</title>{% endblock title %}
{% block link %}
<li><a href="{% url 'interviewer:candidates_list'%}">All Candidates</a></li>
<li><a href="{% url 'interviewer:interviewer_logout'%}">Logout</a></li>
{% endblock link %}
{% block pagetitle %} <h4>Scheduled Events</h4> {% endblock pagetitle %}
{% block content %}
        {% if messages %}
        {% for message in messages %}
        <P>{{message}}</P>
        {% endfor %}
        {% endif %}
        {% if events %}
            <table>
            <tr>
                <th>Candidate Name</th>
                <th>Stack</th>
                <th>Interview Date</th>
                <th>Interview Duration</th>
                <th>Action</th>
            </tr>
        {% for event in events %}
            <tr>
                <td>{{event.candidate.name}}</td>
                <td>{{event.candidate.stack|join:", "}}</td>
                <td>{{event.start}}</td>
                <td>{{event.duration}} Seconds</td>
                <td><a href="{% url 'interviewer:update_event' event_id=event.id %}">Update Event </a>|<a href="{% url 'interviewer:delete_event' event_id=event.id %}">Delete Event</a></td>
            </tr>
        {% endfor %}
        </table>
        {% else %}
            <h3>You do not have any scheduled events yet!</h3>
        {% endif %}
{% endblock content %}

src/interviewer/templates/update_event.html
{% extends "base_interview.html" %}
{% block title %}<title>Uodate Event</title>{% endblock title %}
{% block link %}
<li><a href="{% url 'interviewer:events'%}">My Events</a></li>
<li><a href="{% url 'interviewer:candidates_list'%}">All Candidates</a></li>
<li><a href="{% url 'interviewer:interviewer_logout'%}">Logout</a></li>
{% endblock link %}
{% block pagetitle %} <h4>Update Event</h4> {% endblock pagetitle %}
{% block content %}
    {% if form.non_field_errors %}
    <div>
        {% for err in form.non_field_errors %}
            <p>{{err}}</p>
        {% endfor %}
    </div>
    {% endif %}
    {% if messages %}
    {% for message in messages %}
      <P>{{message}}</P>
    {% endfor %}
    {% endif %}
    <form id='login-form' action="" method='POST'>
      <label for="candidate">CANDIDATE</label>
      <input id="candidate" type="text" readonly value="{{candidate.name}}" required>
      <label for="start_date">EVENT START</label>
      <input type="datetime-local" id="start_date" class="form-control" name="start_date" required placeholder="START DATE.">
      <label for="duration">DURATION(SECONDS)</label>
      <input id="duration" name="duration" type="number" placeholder="00" required>
      <button type='submit'>Update Event</button>
      {% csrf_token %}
    </form>
{% endblock content %}