src/candidate/urls.py
from django.urls import path
from candidate.views import (
    CandidateLoginView,
    CandidateLogoutView,
    EditCandidateView,
    RegisterCandidateView,
    CandidateEventsView,
    CandidateDetailsView
)


urlpatterns = [
    path('register/', RegisterCandidateView.as_view(), name='register_candidate'),
    path('login/', CandidateLoginView.as_view(), name='candidate_login'),
    path('<uuid:candidate_id>/events/', CandidateEventsView.as_view(), name='candidate_events'),
    path('<uuid:candidate_id>/', CandidateDetailsView.as_view(), name='candidate_details'),
    path('<uuid:candidate_id>/edit/', EditCandidateView.as_view(), name='edit_details'),
    path('logout/', CandidateLogoutView.as_view(), name='logout_candidate')
]

src/vgg_interview/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from interviewer.views import IndexView as HomePageView

urlpatterns = [
    re_path(r'^$', HomePageView.as_view(), name='home'),
    path('candidate/', include(('candidate.urls', 'candidate'), namespace='candidate')),
    path('interviewer/',include(('interviewer.urls', 'interviewer'), namespace='interviewer')),
]

src/candidate/forms.py
from django import forms
from django.contrib.postgres.forms import SimpleArrayField
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import make_password

class CandidateRegisterForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField()
    stack = SimpleArrayField(forms.CharField(), required=True)

    def __init__(self, *args, **kwargs):
        """Set up default value for instance objects."""
        self.candidate_user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        """Clean up form an run neccessary validations if any
        """

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

class UpdateCandidateForm(forms.Form):
    name = forms.CharField()
    stack = SimpleArrayField(forms.CharField(), required=True)

    def __init__(self, *args, **kwargs):
        """Set up default value for instance objects."""
        self.candidate_user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        """Clean up form an run neccessary validations if any
        """

        name = self.cleaned_data.get('name')
        stack = self.cleaned_data.get('stack')

class CandidateLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()

    def __init__(self, *args, **kwargs):
        """Set up default value for instance objects.
        """
        self.candidate_user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        """Clean up form an run neccessary validations if any
        """

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

src/candidate/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth import login, logout
from candidate.forms import  CandidateLoginForm, CandidateRegisterForm, UpdateCandidateForm
from accounts.models import User, Candidate, Event
from lib.authentication import CandidateLoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import authenticate
from datetime import datetime, time, timedelta

# Create your views here.
class RegisterCandidateView(View):
    def get(self, request):
        """Render candidate Registration page.
        """
        if request.user.is_authenticated:
            return redirect(reverse('candidate:candidate_events', args=[request.user.id]))
        form = CandidateRegisterForm()
        return render(request, 'register_candidate.html', {'form':form})

    def post(self, request):
        """
        Handle candidate registration.
        """

        form = CandidateRegisterForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.get(email=form.cleaned_data['email'])
                messages.add_message(request, messages.ERROR, 'Candidate with same email already exists!')
                return render(request, 'register_candidate.html', {'form': form})
            except User.DoesNotExist:
                user = User.objects.create_user(
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password']
                )
                candidate = Candidate.objects.create(name=form.cleaned_data['name'], user=user, stack=request.POST.getlist('stack'))
                return redirect(reverse('candidate:candidate_login'))

        return render(request, 'register_candidate.html', {'form': form})

class CandidateLoginView(View):
    def get(self, request):
        """Render candidate login page.
        """

        if request.user.is_authenticated:
            return redirect(reverse('candidate:candidate_events', args=[request.user.id]))

        form = CandidateLoginForm()
        return render(request, 'login_candidate.html')

    def post(self, request):
        """
        Handle candidate login.
        """

        form = CandidateLoginForm(request.POST)
        if form.is_valid():
            candidate_user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])

            if candidate_user:
                login(request, candidate_user, backend='lib.authentication.UserBackend')
                return redirect(reverse('candidate:candidate_events', args=[candidate_user.id]))

        messages.add_message(request, messages.ERROR, 'Invalid Login Credentials')
        return render(request, 'login_candidate.html', {'form': form})

class CandidateDetailsView(CandidateLoginRequiredMixin, View):
    def get(self, request, candidate_id):
        """
        Render Candidate details page.
        """

        candidate = Candidate.objects.get(user=request.user)
        context = {'candidate': candidate}

        return render(request, 'candidate_details.html', context)

class CandidateEventsView(CandidateLoginRequiredMixin, View):
    def get(self, request, candidate_id):
        """
        Render Candidate's events page.
        """

        candidate = Candidate.objects.get(user=request.user)
        upcoming_event = Event.objects.filter(candidate=candidate)
        context = {'upcoming_events':upcoming_event}
        return render(request, 'candidate_events.html', context)


class EditCandidateView(CandidateLoginRequiredMixin, View):
    """
    Edit a Candidate object
    """

    def get(self, request, candidate_id):

        form = UpdateCandidateForm()
        candidate = Candidate.objects.get(user=request.user)
        context = {'form':form, 'candidate':candidate}
        return render(request, 'edit_candidate.html', context)

    def post(self, request, candidate_id):
        form = UpdateCandidateForm(request.POST)
        candidate = Candidate.objects.get(user=request.user)
        if form.is_valid():
            candidate.name = form.cleaned_data['name']
            candidate.required_passes = request.POST.getlist('stack')
            candidate.save()
            messages.add_message(request, messages.SUCCESS, 'Candidate updated successfully')
            return redirect(reverse('candidate:candidate_details', args=[candidate.id]))
        else:
            messages.add_message(request, messages.ERROR, 'Error updating candidate, please select relevant fields')
            return redirect(reverse('candidate:edit_details', args=[candidate.id]))
        context = {'form':form, 'candidate':candidate}
        return render(request, 'edit_candidate.html', context)


class CandidateLogoutView(CandidateLoginRequiredMixin, View):
    def get(self, request):
        """
        Logout candidate.
        """

        request.session.flush()
        logout(request)
        return redirect(reverse('candidate:candidate_login'))

src/candidate/templates/base.html
<!DOCTYPE html>
<html>
<head>
  {% block title %} {% endblock title %}
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}

li {
  display: inline;
}
.content{
    display:flex;
    align-items:center;
    justify-content:center;
    height:80vh;
  }
  form {
    margin:0 auto;
    width:300px
    }
    input {
    margin-bottom:3px;
    padding:10px;
    width: 100%;
    border:1px solid #CCC
    }
    button {
    padding:10px
    }
    label {
    cursor:pointer
    }
    #form-switch {
    display:none
    }
    #register-form {
    display:none
    }
    #form-switch:checked~#register-form {
    display:block
    }
    #form-switch:checked~#login-form {
    display:none
    }
    table, th, td {
    border:1px solid black;
    }
</style>
</head>
<body>

<ul>
  <li><h3>VGG CANDIDATE PORTAL</h3></li>
  {% block link %}{% endblock link %}
</ul>
<div style="text-align: center;">
  {% block pagetitle %} {% endblock pagetitle %}
</div>
<div class="content">
{% block content %}{% endblock content %}
</div>
</body>
</html>

src/candidate/templates/candidate_details.html
{% extends "base.html" %}
{% block title %}<title>Candidate Details</title>{% endblock title %}
{% block link %}
<li><a href="{% url 'candidate:candidate_events' candidate_id=user.id%}">My Events</a></li>
<li><a href="{% url 'candidate:edit_details' candidate_id=user.id%}">Edit Profile</a></li>
<a href="{% url 'candidate:logout_candidate'%}">Logout</a></li>
{% endblock link %}
{% block pagetitle %}<h4>My Profile</h4>{% endblock pagetitle %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
          <P>{{message}}</P>
        {% endfor %}
    {% endif %}
        <table>
        <tr>
            <th>Name</th>
            <th>Stack</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>{{candidate.name}}</td>
            <td>{{candidate.stack|join:", "}}</td>
            <td>
                <a href="{% url 'candidate:edit_details' candidate_id=user.id %}">Update</a>
            </td>
        </tr>

        </table>
{% endblock content %}

src/candidate/templates/candidate_events.html
{% extends "base.html" %}
{% block title %}<title>Candidate Events</title>{% endblock title %}
{% block link %}
<li><a href="{% url 'candidate:candidate_details' candidate_id=user.id%}">My Profile</a></li>
<li><a href="{% url 'candidate:edit_details' candidate_id=user.id%}">Edit Profile</a></li>
<li><a href="{% url 'candidate:logout_candidate'%}">Logout</a></li>
{% endblock link %}
{% block pagetitle %} <h4>My Events</h4> {% endblock pagetitle %}
{% block content %}
{% if upcoming_events %}
        <table>
        <tr>
            <th>Interview Start Time</th>
            <th>Duration</th>
        </tr>
    {% for event in upcoming_events %}
        <tr>
            <td>{{event.start}}</td>
            <td>{{event.duration}} Seconds</td>
        </tr>
    {% endfor %}
    </table>
    {% else %}
        <h3>You do not have any upcoming event yet!</h3>
    {% endif %}
    {% endblock content %}

src/candidate/templates/edit_candidate.html
{% extends "base.html" %}
{% block title %}<title>Edit Candidate</title>{% endblock title %}
{% block link %}
<li><a href="{% url 'candidate:candidate_events' candidate_id=user.id%}">My Events</a></li>
<li><a href="{% url 'candidate:candidate_details' candidate_id=user.id%}">My Profile</a></li>
<a href="{% url 'candidate:logout_candidate'%}">Logout</a></li>
{% endblock link %}
{% block pagetitle %} <h4>Edit Profile</h4> {% endblock pagetitle %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
          <P>{{message}}</P>
        {% endfor %}
    {% endif %}
    <form action="{% url 'candidate:edit_details' candidate_id=user.id %}" method="POST">
    
            <label for="python">NAME</label>
            <div>
                <input type="text" class="form-control" name="name" required placeholder="Full name" value="{{candidate.name}}">
            </div>
            <div>
                <label>STACK</label>
                <div>
                    <input type="checkbox" id="python" name="stack" value="Python"> 
                    <label for="python">Python</label><br>
                    <input type="checkbox" id="django" name="stack" value="Django">
                    <label for="django">Django</label><br>
                    <input type="checkbox" id="celery" name="stack" value="Celery">
                    <label for="celery">Celery</label><br>
                </div>
            </div>
            {% csrf_token %}
            <div >
            <input value="Edit Candidate" id="submit" type="submit" href="#"/>
            </div>
        
        </form>
{% endblock content %}

src/candidate/templates/login_candidate.html
{% extends "base.html" %}
{% block title %}<title>Candidate Login</title>{% endblock title %}
{% block content %}
    {% if form.non_field_errors %}
    <div>
        {% for err in form.non_field_errors %}
            <p>{{err}}</p>
        {% endfor %}
    </div>
    {% endif %}
  {% if messages %}
  {% for message in messages %}
    <P>{{message}}</P>
  {% endfor %}
{% endif %}
    <form id='login-form' action="{% url 'candidate:candidate_login' %}" method='POST'>
      <label for="email">EMAIL</label>
      <input id="email" name="email" type="email" placeholder="Email" required>
      <label for="password">PASSWORD</label>
      <input id="password" name="password" type="password" placeholder="Password" required>
      <button type='submit'>Login Candidate</button>
      <p><a href="{% url 'candidate:register_candidate' %}">Register Instead</a></p>
      {% csrf_token %}
    </form>
{% endblock content %}

src/candidate/templates/register_candidate.html
{% extends "base.html" %}
{% block title %}<title>Candidate Register</title>{% endblock title %}
{% block content %}
        {% if form.non_field_errors %}
        <div>
            {% for err in form.non_field_errors %}
                <p>{{err}}</p>
            {% endfor %}
        </div>
        {% endif %}
        {% if messages %}
        {% for message in messages %}
          <P>{{message}}</P>
        {% endfor %}
        {% endif %}
    <form action="{% url 'candidate:register_candidate' %}" method="POST">
    
            <label for="python">NAME</label>
            <div>
                <input type="text" class="form-control" name="name" required placeholder="Full name" value="">
            </div>
            <label for="python">EMAIL</label>
            <div>
                <input type="email" class="form-control" name="email" required placeholder="Email" value="">
            </div>
            <label for="python">PASSWORD</label>
            <div>
                <input type="password" class="form-control" name="password" required placeholder="Password" value="">
            </div>
            <div>
                <label>STACK</label>
                <div>
                    <input type="checkbox" id="python" name="stack" value="Python"> 
                    <label for="python">Python</label><br>
                    <input type="checkbox" id="django" name="stack" value="Django">
                    <label for="django">Django</label><br>
                    <input type="checkbox" id="celery" name="stack" value="Celery">
                    <label for="celery">Celery</label><br>
                </div>
            </div>
            {% csrf_token %}
            <div >
            <input value="Register Candidate" id="submit" type="submit" href="#"/>
            </div>
            <p><a href="{% url 'candidate:candidate_login' %}">Login Instead</a></p>
        
        </form>
{% endblock content %}